start: prefix json suffix
prefix: "<|start_header_id|>assistant<|end_header_id|>" NL* FREE_TEXT? NL+ CODE_FENCE JSON_TAG? NL
suffix: NL CODE_FENCE
json: "{" NL? WS* kv_pair ("," NL? WS* kv_pair)* NL? WS* "}"
kv_pair: COLUMN WS* ":" WS* STRING

FREE_TEXT: /[a-zA-Z0-9.,-?!;:' ]+/
CODE_FENCE: "```"
JSON_TAG: "json"
WS: " "
NL: "\n"
STRING: /"[a-zA-Z0-9-.,'& ]*"/
# dropped for now: "city"
COLUMN: "\"" ("first" | "last" | "addr" | "addr2" | "specialty" | "city" | "zip" | "legal_name") "\""